image: debian:openssl-build

stages:
    - build         # contains build and test and deploy

variables:
    OPENSSL_BRANCH: "OpenSSL_1_1_0"
    PREBUILTS_REPO: "https://$GIT_USER:$GIT_PASSWORD@gl.viaduck.org/viaduck/openssl-prebuilts.git"
    
linux-x86_64:
    script:
        - mkdir build-linux-x86_64
        - useradd -d /home/jdoe jdoe                                  # OpenSSL tests must be run as unprivileged user
        - cd build-linux-x86_64
        - cmake ../ -DBUILD_OPENSSL=ON -DOPENSSL_BRANCH=$OPENSSL_BRANCH
        - chmod -R 777 .                                              # jdoe must be able to write to build directory
        - su -l jdoe -c "cd `pwd` && make"                            # build and test as unprivileged
        - cd ..
        - scripts/commit_result.sh x86_64-linux build-linux-x86_64
    stage: build
    only:
        - master

windows-x86:
    script:
        - mkdir build-windows-x86
        - cd build-windows-x86
        - cmake ../ -DBUILD_OPENSSL=ON -DOPENSSL_BRANCH=$OPENSSL_BRANCH -DCROSS=ON -DCROSS_PREFIX=i686-w64-mingw32- -DCROSS_TARGET=mingw
        - make
        - cd ..
        - scripts/commit_result.sh i686-w64-mingw32 build-windows-x86
    stage: build
    only:
        - master

windows-x86_64:
    script:
        - mkdir build-windows-x86_64
        - cd build-windows-x86_64
        - cmake ../ -DBUILD_OPENSSL=ON -DOPENSSL_BRANCH=$OPENSSL_BRANCH -DCROSS=ON -DCROSS_PREFIX=x86_64-w64-mingw32- -DCROSS_TARGET=mingw64
        - make
        - cd ..
        - scripts/commit_result.sh x86_64-w64-mingw32 build-windows-x86_64
    stage: build
    only:
        - master
