image: debian:openssl-build

stages:
    - build         # contains build and test
    - deploy
    
openssl-x86_64:
    script:
        - cmake . -DBUILD_OPENSSL=ON
        - make
        - scripts/commit_result.sh x86_64-linux OpenSSL_1_0_2d
    stage: build
    only:
        - master